language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - pip install six pep8 coveralls --use-mirrors
script:
    - coverage run --source=gedcom setup.py test
    - pep8 --max-line-length=200 gedcom
after_success:
    - coveralls
